### ISSUE TITLE
multiple reload guard not set up

### ISSUE THREAD

**Issue by guyzmo** [tweekmonster/anyline.vim#1]
In your plugin you check for `g:anyline` but you're not setting it up:

```
if !exists('g:anyline')
```

you should either check for existence of `g:anyline_custom_statusline`:

```
if !exists('g:anyline_custom_statusline')
```

or set anyline:

```
if !exists('g:anyline')
    let g:anyline = 1
```

**Comment by tweekmonster** [comment]
I can't believe this slipped!  I've fixed the issue and added unit tests so this doesn't happen again.

**Comment by tweekmonster** [comment]
I also added a Travis-CI badge to README.md to assure visitors that this plugin is high quality.
